server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orderings/**, 
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliverings/**, 
        - id: items
          uri: http://localhost:8083
          predicates:
            - Path=/stackings/**, 
        - id: mypage
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orderings/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliverings/**, 
        - id: items
          uri: http://items:8080
          predicates:
            - Path=/stackings/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
